name: flutter_mvvm_frame
description: Flutter fast-developing frame with MVVM mode
version: 1.0.4+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  shared_preferences: ^2.0.5
  event_bus: ^2.0.0
  rxdart: ^0.27.1
  get: ^4.1.4
  moor: ^4.3.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.1
  path: ^1.8.0
  connectivity_plus: ^1.0.1
  fluttertoast: ^8.0.7
  device_info: ^2.0.1
  permission_handler: ^8.1.4+2
  package_info: ^2.0.2
  crypto: ^3.0.1
  webview_flutter: ^2.0.8
  intl: ^0.17.0
  r_dart_library: 0.4.0-nullsafety.0
  json_serializable: ^4.1.2
  timezone: ^0.7.0
  encrypt: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  moor_generator: ^4.3.0
flutter:
  uses-material-design: true
  assets:
  - packages/flutter_mvvm_frame/assets/texts/jsons/city.json
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - lib/assets/images
  - lib/assets/texts
  fonts:
  - lib/assets/fonts
